### ISSUE TITLE
Copyright information

### ISSUE THREAD

**Issue by frthjf** [ayulockin/SwAV-TF#10]
Hi there, 
I've noticed that the code files do not seem to declare [a copyright header](https://github.com/ayulockin/SwAV-TF/blob/master/LICENSE#L178). What's the copyright information on this code?

**Comment by sayakpaul** [comment]
We don't have a header. As long as our work is duly cited, we are good and we trust that the honest developers would do that anyway. Hence, we only have a [license](https://github.com/ayulockin/SwAV-TF/blob/master/LICENSE).
