### ISSUE TITLE
image loaders don't produce augmentations from the same image

### ISSUE THREAD

**Issue by AmrKhalifa** [ayulockin/SwAV-TF#11]
Hi, I was looking into the notebook initial_notebooks/MultiCropDataset_Architecture.ipynb

and I am curious, when visualizing the images from im1, im2, im3 tensors 
why do they contain different images,
for instance, I would expect 
im1[0], im2[0], im3[0]. to be different augmentations from the same image, but this is not the case here. I am probably getting something wrong.

**Comment by AmrKhalifa** [comment]
great, thanks !

**Comment by yuvaramsingh94** [comment]
hi i tried to set options = None but this did not help in my case . i set the seed=1 on the `shuffle(1024)`  (multicrop_dataset.py) and set `options.experimental_deterministic=True` . this helped me solve the issue . pls suggest if this is a correct method to do

**Comment by sayakpaul** [comment]
Yes, it's correct. You can also disable all the options that come from `tf.data.Options()`.
