### ISSUE TITLE
Classify a single image

### ISSUE THREAD

**Issue by VivianaFigueira** [ayulockin/SwAV-TF#12]
Hello :)
How could I predict the label of a single new image after the SwAV training and linear evaluation ?
Thank you!

**Comment by ayulockin** [comment]
Hey @VivianaFigueira, you will take the backbone model you pretrained using SwAV and do something like `model.predict(image)`. This should give you a prediction on a single image.

However, the data (image) should be preprocessed as per the model's requirement.

**Comment by VivianaFigueira** [comment]
Thank you so much :)

**Comment by VivianaFigueira** [comment]
Hello, so I'm still having trouble to predict an image because of the preprocess required. 

The train_ds is a Prefetch Dataset: <PrefetchDataset element_spec=(TensorSpec(shape=(None, None, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))> and what comes out after applying multicrop is
<_OptionsDataset element_spec=TensorSpec(shape=(224, 224, 3), dtype=tf.float32, name=None) ...

If I would use a custom dataset could I pass it to have the same types, shapes as the prefetch dataset flowers or would I have to adapt the code to do the same but with my array type custom dataset ? 

Appreciate the help!
